export const ReportsErrors = {
  REPORT_FETCH_FAILED: 'REPORT_FETCH_FAILED',
  REPORT_INVALID_RANGE: 'REPORT_INVALID_RANGE',
  REPORT_NO_DATA: 'REPORT_NO_DATA',
  REPORT_INVALID_TENANT_ID: 'REPORT_INVALID_TENANT_ID',
  REPORT_INVALID_FILTERS: 'REPORT_INVALID_FILTERS',
  REPORT_CUSTOM_RANGE_MISSING_DATES: 'REPORT_CUSTOM_RANGE_MISSING_DATES',
  REPORT_CUSTOM_RANGE_INVERTED: 'REPORT_CUSTOM_RANGE_INVERTED',
  REPORT_LIMIT_INVALID: 'REPORT_LIMIT_INVALID',
} as const;
