/** Production Error Codes - PROD-001..012 */

export const ProductionErrors = {
  // Recipe errors
  RECIPE_NOT_FOUND: 'PRODUCTION_RECIPE_NOT_FOUND',
  RECIPE_DUPLICATE_PRODUCT: 'PRODUCTION_RECIPE_DUPLICATE_PRODUCT',
  RECIPE_DUPLICATE_NAME: 'PRODUCTION_RECIPE_DUPLICATE_NAME',
  RECIPE_NO_INGREDIENTS: 'PRODUCTION_RECIPE_NO_INGREDIENTS',
  RECIPE_PRODUCT_NOT_FOUND: 'PRODUCTION_RECIPE_PRODUCT_NOT_FOUND',
  RECIPE_INGREDIENT_NOT_FOUND: 'PRODUCTION_RECIPE_INGREDIENT_NOT_FOUND',
  RECIPE_YIELD_INVALID: 'PRODUCTION_RECIPE_YIELD_INVALID',
  RECIPE_MODE_INVALID: 'PRODUCTION_RECIPE_MODE_INVALID',
  RECIPE_NAME_REQUIRED: 'PRODUCTION_RECIPE_NAME_REQUIRED',
  RECIPE_INACTIVE: 'PRODUCTION_RECIPE_INACTIVE',
  RECIPE_INVALID_INPUT: 'PRODUCTION_RECIPE_INVALID_INPUT',
  RECIPE_PRODUCT_TYPE_INVALID: 'PRODUCTION_RECIPE_PRODUCT_TYPE_INVALID',
  RECIPE_INGREDIENT_TYPE_INVALID: 'PRODUCTION_RECIPE_INGREDIENT_TYPE_INVALID',
  RECIPE_CREATE_FAILED: 'PRODUCTION_RECIPE_CREATE_FAILED',
  RECIPE_UPDATE_FAILED: 'PRODUCTION_RECIPE_UPDATE_FAILED',
  RECIPE_HAS_ORDERS: 'PRODUCTION_RECIPE_HAS_ORDERS',
  RECIPE_DELETE_FAILED: 'PRODUCTION_RECIPE_DELETE_FAILED',
  RECIPE_PRODUCT_NO_STOCK: 'PRODUCTION_RECIPE_PRODUCT_NO_STOCK',
  RECIPE_INGREDIENT_NO_STOCK: 'PRODUCTION_RECIPE_INGREDIENT_NO_STOCK',
  RECIPE_INGREDIENT_EXCEEDS_STOCK: 'PRODUCTION_RECIPE_INGREDIENT_EXCEEDS_STOCK',

  // PRODUCTION-003 [Paso-2]: Auto-creación de producto_terminado
  RECIPE_PRODUCT_NAME_REQUIRED: 'PRODUCTION_RECIPE_PRODUCT_NAME_REQUIRED',
  RECIPE_PRODUCT_SKU_REQUIRED: 'PRODUCTION_RECIPE_PRODUCT_SKU_REQUIRED',
  RECIPE_PRODUCT_PRICE_REQUIRED: 'PRODUCTION_RECIPE_PRODUCT_PRICE_REQUIRED',
  RECIPE_INVALID_PRODUCT_TYPE: 'PRODUCTION_RECIPE_INVALID_PRODUCT_TYPE',
  RECIPE_PRODUCT_SKU_DUPLICATE: 'PRODUCTION_RECIPE_PRODUCT_SKU_DUPLICATE',

  // Sub-receta errors (PRODUCTION-001-008)
  RECIPE_CYCLE_DETECTED: 'PRODUCTION_RECIPE_CYCLE_DETECTED',
  RECIPE_MAX_DEPTH_EXCEEDED: 'PRODUCTION_RECIPE_MAX_DEPTH_EXCEEDED',
  SUB_RECIPE_INACTIVE: 'PRODUCTION_SUB_RECIPE_INACTIVE',
  SUB_RECIPE_NOT_FOUND: 'PRODUCTION_SUB_RECIPE_NOT_FOUND',

  // Production Order errors
  ORDER_NOT_FOUND: 'PRODUCTION_ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS: 'PRODUCTION_ORDER_INVALID_STATUS',
  ORDER_INVALID_INPUT: 'PRODUCTION_ORDER_INVALID_INPUT',
  ORDER_INSUFFICIENT_STOCK: 'PRODUCTION_ORDER_INSUFFICIENT_STOCK',
  ORDER_BATCH_COUNT_INVALID: 'PRODUCTION_ORDER_BATCH_COUNT_INVALID',
  ORDER_BATCH_COUNT_EXCEEDED: 'PRODUCTION_ORDER_BATCH_COUNT_EXCEEDED',
  ORDER_RECIPE_NOT_BATCH: 'PRODUCTION_ORDER_RECIPE_NOT_BATCH',

  // Assembly errors
  ASSEMBLY_NO_RECIPE: 'PRODUCTION_ASSEMBLY_NO_RECIPE',
  ASSEMBLY_INSUFFICIENT_STOCK: 'PRODUCTION_ASSEMBLY_INSUFFICIENT_STOCK',
  ASSEMBLY_PRODUCT_NOT_FOUND: 'PRODUCTION_ASSEMBLY_PRODUCT_NOT_FOUND',
  ASSEMBLY_FAILED: 'PRODUCTION_ASSEMBLY_FAILED',

  // PRODUCTION-003 [Paso-3]: Errores del helper compartido de consumo FIFO real
  // Usados por calculateConsumptionCost (costCalculator) y por los callers refactorizados.
  INGREDIENT_INSUFFICIENT_STOCK: 'PRODUCTION_INGREDIENT_INSUFFICIENT_STOCK',
  INGREDIENT_NOT_FOUND: 'PRODUCTION_INGREDIENT_NOT_FOUND',
} as const;

export type ProductionErrorCode = typeof ProductionErrors[keyof typeof ProductionErrors];
