export const InventoryErrors = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_DUPLICATE: 'PRODUCT_SKU_DUPLICATE',
  PRODUCT_WEIGHTED_PRECISION: 'PRODUCT_WEIGHTED_PRECISION',
  INVENTORY_STOCK_INSUFFICIENT: 'INVENTORY_STOCK_INSUFFICIENT',
  WEIGHTED_MOVEMENT_QUANTITY_INVALID: 'WEIGHTED_MOVEMENT_QUANTITY_INVALID',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
} as const;