export const InventoryErrors = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SKU_DUPLICATE: 'PRODUCT_SKU_DUPLICATE',
  PRODUCT_HAS_STOCK: 'PRODUCT_HAS_STOCK',
  INVENTORY_STOCK_INSUFFICIENT: 'INVENTORY_STOCK_INSUFFICIENT',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  INVENTORY_LOT_FIFO_CONFLICT: 'INVENTORY_LOT_FIFO_CONFLICT',
  PRESENTATION_NOT_FOUND: 'PRESENTATION_NOT_FOUND',
  PRESENTATION_NAME_REQUIRED: 'PRESENTATION_NAME_REQUIRED',
  PRESENTATION_MULTIPLIER_INVALID: 'PRESENTATION_MULTIPLIER_INVALID',
} as const;
