export const PosErrors = {
  SALE_BOX_CLOSED: 'SALE_BOX_CLOSED',
  SALE_IGTF_INVALID: 'SALE_IGTF_INVALID',
  SALE_TOTALS_MISMATCH: 'SALE_TOTALS_MISMATCH',
  SALE_NO_ITEMS: 'SALE_NO_ITEMS',
  SALE_STOCK_INSUFFICIENT: 'SALE_STOCK_INSUFFICIENT',
  SALE_EXCHANGE_RATE_NOT_FOUND: 'SALE_EXCHANGE_RATE_NOT_FOUND',
  BOX_ALREADY_OPEN: 'BOX_ALREADY_OPEN',
  BOX_ALREADY_CLOSED: 'BOX_ALREADY_CLOSED',
  BOX_OPENING_BALANCE_REQUIRED: 'BOX_OPENING_BALANCE_REQUIRED',
  BOX_CLOSING_BALANCE_REQUIRED: 'BOX_CLOSING_BALANCE_REQUIRED',
  CART_ITEM_WEIGHT_REQUIRED: 'CART_ITEM_WEIGHT_REQUIRED',
  BOX_QUERY_FAILED: 'BOX_QUERY_FAILED',
  BOX_CLOSED_TODAY: 'BOX_CLOSED_TODAY',
  // AUDIT-FLOW-12-012: Anulación post-cierre aborta para no corromper arqueo.
  SALE_VOID_BOX_CLOSED: 'SALE_VOID_BOX_CLOSED',
} as const;
