export const DashboardErrors = {
  DASHBOARD_LOAD_FAILED: 'DASHBOARD_LOAD_FAILED',
  DASHBOARD_BOX_CLOSED: 'DASHBOARD_BOX_CLOSED',
  TENANT_INFO_FAILED: 'TENANT_INFO_FAILED',
  SUBSCRIPTION_INFO_FAILED: 'SUBSCRIPTION_INFO_FAILED',
  EMPLOYEES_LOAD_FAILED: 'EMPLOYEES_LOAD_FAILED',
  TASA_BCV_FETCH_FAILED: 'TASA_BCV_FETCH_FAILED',
  TASA_INVALID_RATE: 'TASA_INVALID_RATE',
  TASA_API_ERROR: 'TASA_API_ERROR',
  MODULE_NOT_IMPLEMENTED: 'MODULE_NOT_IMPLEMENTED',
} as const;