export const DashboardErrors = {
  DASHBOARD_LOAD_FAILED: 'DASHBOARD_LOAD_FAILED',
  DASHBOARD_TODAY_EARNINGS_FAILED: 'DASHBOARD_TODAY_EARNINGS_FAILED',
  DASHBOARD_TOP_PRODUCTS_FAILED: 'DASHBOARD_TOP_PRODUCTS_FAILED',
  DASHBOARD_ACTIVITY_FAILED: 'DASHBOARD_ACTIVITY_FAILED',
  EMPLOYEES_LOAD_FAILED: 'EMPLOYEES_LOAD_FAILED',
  SUBSCRIPTION_INFO_FAILED: 'SUBSCRIPTION_INFO_FAILED',
  TENANT_INFO_FAILED: 'TENANT_INFO_FAILED',
} as const;
