/** Purchases Error Codes - PURCH-001..005 */

export const PurchaseErrors = {
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  SUPPLIER_HAS_ORDERS: 'SUPPLIER_HAS_ORDERS',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  ORDER_ALREADY_RECEIVED: 'ORDER_ALREADY_RECEIVED',
  ORDER_RECEIVE_EXCEEDS: 'ORDER_RECEIVE_EXCEEDS',
  ORDER_CANCEL_NOT_ALLOWED: 'ORDER_CANCEL_NOT_ALLOWED',
} as const;

export type PurchaseErrorCode = typeof PurchaseErrors[keyof typeof PurchaseErrors];
