export const PurchasesErrors = {
  PURCHASE_NOT_CONFIRMED: 'PURCHASE_NOT_CONFIRMED',
  PURCHASE_RECEIVING_TOTALS_MISMATCH: 'PURCHASE_RECEIVING_TOTALS_MISMATCH',
  PURCHASE_ORDER_NOT_FOUND: 'PURCHASE_ORDER_NOT_FOUND',
  INVENTORY_LOT_FIFO_CONFLICT: 'INVENTORY_LOT_FIFO_CONFLICT',
} as const;