/** Purchases Error Codes - PURCH-001..005 */

export const PurchaseErrors = {
  SUPPLIER_NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  SUPPLIER_HAS_ORDERS: 'SUPPLIER_HAS_ORDERS',
  SUPPLIER_INVALID_INPUT: 'SUPPLIER_INVALID_INPUT',
  SUPPLIER_RIF_DUPLICATE: 'SUPPLIER_RIF_DUPLICATE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  ORDER_ALREADY_RECEIVED: 'ORDER_ALREADY_RECEIVED',
  ORDER_RECEIVE_EXCEEDS: 'ORDER_RECEIVE_EXCEEDS',
  ORDER_CANCEL_NOT_ALLOWED: 'ORDER_CANCEL_NOT_ALLOWED',
  SUPPLIER_NO_DEBT: 'SUPPLIER_NO_DEBT',
  ORDER_NOT_PENDING: 'ORDER_NOT_PENDING',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  PAYMENT_EXCEEDS_DEBT: 'PAYMENT_EXCEEDS_DEBT',
  PAYMENT_EXCEEDS_ORDER_BALANCE: 'PAYMENT_EXCEEDS_ORDER_BALANCE',
} as const;

export type PurchaseErrorCode = typeof PurchaseErrors[keyof typeof PurchaseErrors];
