export const AuthErrors = {
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_NO_SESSION: 'AUTH_NO_SESSION',
  AUTH_NO_ROLE: 'AUTH_NO_ROLE',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_SCOPE_DENIED: 'AUTH_SCOPE_DENIED',
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
} as const;
