export const AdminErrors = {
  ADMIN_ONLY: 'ADMIN_ONLY',
  TENANT_SLUG_DUPLICATE: 'TENANT_SLUG_DUPLICATE',
  TENANT_RIF_INVALID: 'TENANT_RIF_INVALID',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  TENANT_DELETE_FAILED: 'TENANT_DELETE_FAILED',
  TENANT_HARD_DELETE_FAILED: 'TENANT_HARD_DELETE_FAILED',
  ADMIN_RESET_PASS_FAILED: 'ADMIN_RESET_PASS_FAILED',
  ADMIN_RESTORE_FAILED: 'ADMIN_RESTORE_FAILED',
  ADMIN_ANALYTICS_FAILED: 'ADMIN_ANALYTICS_FAILED',
} as const;
