export const AuthErrors = {
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_NO_SESSION: 'AUTH_NO_SESSION',
  AUTH_NO_ROLE: 'AUTH_NO_ROLE',
  AUTH_SESSION_ACTIVE: 'AUTH_SESSION_ACTIVE',
  AUTH_SCOPE_DENIED: 'AUTH_SCOPE_DENIED',
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  FORBIDDEN_NO_ROLE: 'FORBIDDEN_NO_ROLE',
  AUTH_SUBSCRIPTION_EXPIRED: 'AUTH_SUBSCRIPTION_EXPIRED',
} as const;

export type AuthErrorCode = typeof AuthErrors[keyof typeof AuthErrors];

export function isAuthErrorCode(code: string): code is AuthErrorCode {
  return Object.values(AuthErrors).includes(code as AuthErrorCode);
}
