export const AdminErrors = {
  ADMIN_ONLY: 'ADMIN_ONLY',
  TENANT_SLUG_DUPLICATE: 'TENANT_SLUG_DUPLICATE',
  TENANT_RIF_INVALID: 'TENANT_RIF_INVALID',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_CREATE_FAILED: 'TENANT_CREATE_FAILED',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  ADMIN_USER_CREATE_FAILED: 'ADMIN_USER_CREATE_FAILED',
  SUBSCRIPTION_RENEW_FAILED: 'SUBSCRIPTION_RENEW_FAILED',
  ADMIN_PLAN_PRODUCT_LIMIT_EXCEEDED: 'ADMIN_PLAN_PRODUCT_LIMIT_EXCEEDED',
  ADMIN_PLAN_INVOICE_LIMIT_EXCEEDED: 'ADMIN_PLAN_INVOICE_LIMIT_EXCEEDED',
  ADMIN_PLAN_USER_LIMIT_EXCEEDED: 'ADMIN_PLAN_USER_LIMIT_EXCEEDED',
} as const;
